version: 2

models:
  - name: dim_products
    description: "Dimension table for products, containing product details such as name, price, and supplier information."
    columns:
      - name: ProductID
        description: "Unique identifier for each product."
        tests:
          - not_null
          - unique
      - name: ProductName
        description: "Name of the product."
        tests:
          - not_null
      - name: SupplierID
        description: "Identifier for the supplier of the product."
      - name: QuantityPerUnit
        description: "Details of the product quantity per unit."
      - name: UnitPrice
        description: "Price per unit of the product."
        tests:
          - not_null

  - name: fact_orders
    description: "Fact table capturing details of orders, including products, customers, and order amounts."
    columns:
      - name: OrderID
        description: "Unique identifier for each order."
        #tests:
         # - not_null
        #- unique
      - name: CustomerID
        description: "Unique identifier for the customer placing the order."
        tests:
          - not_null
      - name: ProductID
        description: "Identifier of the product in the order."
        tests:
          - not_null
      - name: OrderDate
        description: "Date when the order was placed."
        tests:
          - not_null
   
  - name: fact_sales_by_products
    description: "Fact table summarizing sales by product, including total quantities and total sales."
    columns:
      - name: ProductID
        description: "Identifier for the product."
        tests:
          - not_null
      - name: total_units_sold
        description: "Total quantity sold for each product."
        tests:
          - not_null
          - accepted_values:
              values: [">= 0"]  # Ensures total quantity is non-negative
      - name: total_sales_value
        description: "Total sales revenue for each product."
        tests:
          - not_null
          - accepted_values:
              values: [">= 0"]  # Ensures total sales are non-negative


sources:
  - name: customer_source  # You can give it any name you prefer
    schema: dbo  # Replace with the schema where your 'Customer' table resides
    database: DBT_PROJECT  # The database where the 'Customer' table is located
    tables:
      - name: Customers  # The name of the source table you want to pull data from
        description: "This table contains customer information."
  
      - name: Products  # The name of the source table you want to pull data from
        description: "This table contains Products information."
      - name: Orders  # The name of the source table you want to pull data from
        description: "This table contains Products information."

      - name: Order_Details  # The name of the source table you want to pull data from
        description: "This table contains Products information."
